on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
jobs:
    call-codecov:
        uses: fortio/workflows/.github/workflows/codecov.yml@main
    call-codeql:
        uses: fortio/workflows/.github/workflows/codeql-analysis.yml@main
    call-releaser:
        uses: fortio/workflows/.github/workflows/releaser.yml@main
